<a href="https://colab.research.google.com/github/FKz11/NN_PyTorch/blob/main/lesson_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# lesson-1

In [1]:
import torch

## 1. Создайте случайный FloatTensor размера 3x4x5

In [2]:
a = torch.rand(3,4,5)
print(a.type())
a.shape

torch.FloatTensor


torch.Size([3, 4, 5])

## 2. Выведите его форму (shape)

In [3]:
a.shape

torch.Size([3, 4, 5])

## 3. Приведите его к форме 6х10

In [4]:
a = a.reshape(6,10)
a.shape

torch.Size([6, 10])

## 4. Создайте случайный IntTensor размера 10

In [5]:
b = torch.randint(10, size=(10,), dtype=torch.int32)
print(b.type())
print(b.shape)

torch.IntTensor
torch.Size([10])


## 5. Умножьте созданный FloatTensor на созданный IntTensor поэлементно

In [6]:
c = a * b.repeat(a.shape[0],1).float()
c

tensor([[1.9362, 5.9080, 0.0371, 0.3186, 1.6257, 8.3715, 1.2974, 0.0000, 7.1679,
         2.5123],
        [4.9494, 1.2651, 0.3116, 0.7301, 1.8542, 3.7391, 2.8227, 0.0000, 5.2013,
         8.4760],
        [2.5147, 5.8074, 0.0158, 0.4230, 1.2687, 8.3038, 2.1336, 0.0000, 6.5195,
         4.0889],
        [1.1105, 5.9503, 0.3865, 0.9718, 2.5354, 6.7787, 1.0747, 0.0000, 1.7376,
         0.4973],
        [1.7688, 5.4870, 0.8549, 0.4170, 0.0694, 6.7173, 1.7399, 0.0000, 5.3720,
         3.8572],
        [4.5439, 5.4715, 1.0908, 0.8555, 2.6015, 1.5903, 1.8445, 0.0000, 0.3615,
         6.3252]])

## 6. Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
## Подсказка: .dot может не подойти

In [7]:
d = c @ c.T
d.shape

torch.Size([6, 6])

## 7. Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

In [8]:
x = torch.tensor([1.,0.5,2.], requires_grad=True)
y = x[0]**3 + x[1] - 75*x[2]
y.backward()
x.grad.sum()

tensor(-71.)

## 8. Создайте единичный тензор размера 5x6

In [9]:
z = torch.ones((5,6))
z

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

## 9. Переведите его в формат numpy

In [10]:
z = z.numpy()
z

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)